-- Create mock profiles for testing Solmates app
-- This creates fake user profiles based on real crypto/tech Twitter accounts

-- Profile #1: Solana Mobile
INSERT INTO users (
  privy_user_id,
  wallet_address,
  username,
  display_name,
  bio,
  twitter_username,
  twitter_name,
  twitter_avatar_url,
  skills,
  interests,
  looking_for,
  location,
  twitter_url,
  website_url,
  experience_level,
  availability,
  verified,
  reputation_score,
  profile_completed,
  is_active
) VALUES (
  'mock_user_solanamobile_' || floor(random() * 1000000),
  '7BgBvyjrZX8YYdZ4KjN3qN8pN9yTQKW1rP2jV5cQ3hWx',
  'solanamobile',
  'Solana Mobile',
  'Building the future of mobile Web3 📱⚡ Creators of Saga phone and Seeker. Bringing crypto to your pocket with native Solana integration.',
  'solanamobile',
  'Solana Mobile',
  'https://pbs.twimg.com/profile_images/1598103201574912000/d7jMFI7k_400x400.jpg',
  ARRAY['Mobile Development', 'Blockchain', 'Solana', 'Hardware', 'Product Design', 'Web3 UX', 'Cryptocurrency', 'DeFi'],
  ARRAY['Mobile Innovation', 'Crypto Adoption', 'DeFi', 'NFTs', 'Developer Tools', 'Web3 Gaming'],
  ARRAY['Technical Co-founder', 'Mobile Engineers', 'Product Managers', 'Business Development', 'Marketing Partners'],
  'Global',
  'https://twitter.com/solanamobile',
  'https://solanamobile.com',
  'expert',
  'full-time',
  true,
  95,
  true,
  true
);

-- Profile #2: Anatoly Yakovenko (Solana Co-founder)
INSERT INTO users (
  privy_user_id,
  wallet_address,
  username,
  display_name,
  bio,
  twitter_username,
  twitter_name,
  twitter_avatar_url,
  skills,
  interests,
  looking_for,
  location,
  twitter_url,
  website_url,
  experience_level,
  availability,
  verified,
  reputation_score,
  profile_completed,
  is_active
) VALUES (
  'mock_user_aeyakovenko_' || floor(random() * 1000000),
  '8QdVdx2N1pJ4vY8rK9mC3hW7xF6tS2nR5qE9lP1oA3bZ',
  'aeyakovenko',
  'Anatoly Yakovenko',
  'Co-founder @solana. Building high-performance blockchain infrastructure. Former Qualcomm. Passionate about consensus algorithms and distributed systems.',
  'aeyakovenko',
  'Anatoly Yakovenko',
  'https://pbs.twimg.com/profile_images/1526664761077731329/Y-53lNsL_400x400.jpg',
  ARRAY['Blockchain Architecture', 'Distributed Systems', 'Consensus Algorithms', 'Systems Programming', 'Rust', 'C++', 'Protocol Design'],
  ARRAY['High Performance Computing', 'Cryptography', 'Network Protocols', 'Open Source', 'Decentralization'],
  ARRAY['Core Engineers', 'Protocol Researchers', 'Systems Architects', 'Blockchain Developers', 'Technical Advisors'],
  'San Francisco, CA',
  'https://twitter.com/aeyakovenko',
  'https://solana.com',
  'expert',
  'full-time',
  true,
  98,
  true,
  true
);

-- Profile #3: Solana Foundation
INSERT INTO users (
  privy_user_id,
  wallet_address,
  username,
  display_name,
  bio,
  twitter_username,
  twitter_name,
  twitter_avatar_url,
  skills,
  interests,
  looking_for,
  location,
  twitter_url,
  website_url,
  experience_level,
  availability,
  verified,
  reputation_score,
  profile_completed,
  is_active
) VALUES (
  'mock_user_solana_' || floor(random() * 1000000),
  '9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM',
  'solana',
  'Solana',
  'A high-performance blockchain supporting builders around the world creating crypto apps that scale today. 🌐 Built by @solanalabs',
  'solana',
  'Solana',
  'https://pbs.twimg.com/profile_images/1583266018916220928/8AxaJcsN_400x400.jpg',
  ARRAY['Blockchain Development', 'DeFi', 'Smart Contracts', 'Web3', 'Ecosystem Growth', 'Developer Relations', 'Community Building'],
  ARRAY['Decentralization', 'DeFi Innovation', 'NFTs', 'Gaming', 'DePIN', 'RealFi', 'Developer Tools'],
  ARRAY['Developers', 'Validators', 'Ecosystem Partners', 'Community Managers', 'Technical Writers', 'DevRel Engineers'],
  'Global',
  'https://twitter.com/solana',
  'https://solana.com',
  'expert',
  'full-time',
  true,
  97,
  true,
  true
);

-- Profile #4: Solana Spaces
INSERT INTO users (
  privy_user_id,
  wallet_address,
  username,
  display_name,
  bio,
  twitter_username,
  twitter_name,
  twitter_avatar_url,
  skills,
  interests,
  looking_for,
  location,
  twitter_url,
  website_url,
  experience_level,
  availability,
  verified,
  reputation_score,
  profile_completed,
  is_active
) VALUES (
  'mock_user_solanaspaces_' || floor(random() * 1000000),
  '5KvY2WqJ8nP7dR6mF3hS9cL1xB4tE2wQ9vN8oA7zM6pU',
  'solanaspaces',
  'Solana Spaces',
  'The first physical retail, education, and community space dedicated to Solana. Experience Web3 IRL. 🏪⚡',
  'solanaspaces',
  'Solana Spaces',
  'https://pbs.twimg.com/profile_images/1635703048234917890/eAq5rO7u_400x400.jpg',
  ARRAY['Retail Experience', 'Community Building', 'Web3 Education', 'Event Management', 'Customer Experience', 'Marketing', 'Brand Strategy'],
  ARRAY['Physical Retail', 'Web3 Adoption', 'Community Events', 'Education', 'Customer Onboarding', 'Experiential Marketing'],
  ARRAY['Community Managers', 'Event Coordinators', 'Educators', 'Retail Partners', 'Marketing Specialists', 'UX Designers'],
  'New York, NY',
  'https://twitter.com/solanaspaces',
  'https://solanaspaces.com',
  'advanced',
  'full-time',
  true,
  88,
  true,
  true
);

-- Profile #5: pump.fun
INSERT INTO users (
  privy_user_id,
  wallet_address,
  username,
  display_name,
  bio,
  twitter_username,
  twitter_name,
  twitter_avatar_url,
  skills,
  interests,
  looking_for,
  location,
  twitter_url,
  website_url,
  experience_level,
  availability,
  verified,
  reputation_score,
  profile_completed,
  is_active
) VALUES (
  'mock_user_pumpdotfun_' || floor(random() * 1000000),
  '3RkJ7qM9wP2nF5dS8cY6tB1xL4vE9oQ7rN3mA5zK8pW',
  'pumpdotfun',
  'pump.fun',
  'the fun way to trade. built on solana. 🚀💰 Trade memecoins, create tokens, and ride the pump!',
  'pumpdotfun',
  'pump.fun',
  'https://pbs.twimg.com/profile_images/1756399564382461952/jJ7nk5xT_400x400.jpg',
  ARRAY['DeFi Development', 'Token Economics', 'Trading Platforms', 'Solana Development', 'Smart Contracts', 'Product Strategy'],
  ARRAY['Memecoins', 'DeFi Trading', 'Token Creation', 'Liquidity Pools', 'Community Tokens', 'Viral Marketing'],
  ARRAY['DeFi Developers', 'Token Economists', 'Community Builders', 'Growth Hackers', 'Frontend Engineers', 'Product Managers'],
  'Remote',
  'https://twitter.com/pumpdotfun',
  'https://pump.fun',
  'expert',
  'flexible',
  true,
  92,
  true,
  true
);

-- Profile #6: Solflare
INSERT INTO users (
  privy_user_id,
  wallet_address,
  username,
  display_name,
  bio,
  twitter_username,
  twitter_name,
  twitter_avatar_url,
  skills,
  interests,
  looking_for,
  location,
  twitter_url,
  website_url,
  experience_level,
  availability,
  verified,
  reputation_score,
  profile_completed,
  is_active
) VALUES (
  'mock_user_solflare_' || floor(random() * 1000000),
  '6VmK3jN8oP4dR7qS9cF2xB5tE1wQ3vN7mA4zL8pU6kY',
  'solflare',
  'Solflare',
  'Non-custodial Solana wallet. Your keys, your crypto. Available on web, mobile & browser extension. 🔑⚡',
  'solflare',
  'Solflare',
  'https://pbs.twimg.com/profile_images/1644041588568313856/3Znh8UvY_400x400.jpg',
  ARRAY['Wallet Development', 'Security Engineering', 'Mobile Development', 'Browser Extensions', 'Cryptography', 'UX Design'],
  ARRAY['Self-Custody', 'Security', 'DeFi Integration', 'NFT Management', 'Multi-Platform', 'User Experience'],
  ARRAY['Security Engineers', 'Mobile Developers', 'Frontend Engineers', 'UX Designers', 'Product Managers', 'DevOps Engineers'],
  'Global',
  'https://twitter.com/solflare',
  'https://solflare.com',
  'expert',
  'full-time',
  true,
  94,
  true,
  true
);

-- Profile #7: Backpack
INSERT INTO users (
  privy_user_id,
  wallet_address,
  username,
  display_name,
  bio,
  twitter_username,
  twitter_name,
  twitter_avatar_url,
  skills,
  interests,
  looking_for,
  location,
  twitter_url,
  website_url,
  experience_level,
  availability,
  verified,
  reputation_score,
  profile_completed,
  is_active
) VALUES (
  'mock_user_backpack_' || floor(random() * 1000000),
  '4TqL8mN6wP3nF2dS7cY5tB9xL1vE4oQ6rN8mA2zK5pW',
  'backpack',
  'Backpack',
  'A home for your xNFTs. The crypto super app. Built by @madlads and @coral_xyz 🎒✨',
  'backpack',
  'Backpack',
  'https://pbs.twimg.com/profile_images/1678840180628459528/iu5I2F8-_400x400.jpg',
  ARRAY['App Development', 'xNFT Platform', 'Wallet Infrastructure', 'Multi-Chain', 'Product Design', 'Developer Tools'],
  ARRAY['xNFTs', 'Multi-Chain Apps', 'Developer Experience', 'App Ecosystem', 'Cross-Platform', 'Innovation'],
  ARRAY['App Developers', 'xNFT Creators', 'Product Engineers', 'Platform Engineers', 'Developer Advocates', 'Community Builders'],
  'San Francisco, CA',
  'https://twitter.com/backpack',
  'https://backpack.app',
  'expert',
  'full-time',
  true,
  93,
  true,
  true
);